examples: Create ima_gen_signing_key_selfsigned function and use it
Create ima_gen_signing_key_localca function for creating an IMA signing key
that also has a self-signed certificate and use it by existing scripts.
Move code from ima-genkey-self-ecc.sh and ima-genkey-self.sh into it.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/examples/functions b/examples/functions
--- a/examples/functions
+++ b/examples/functions
@@ -124,3 +124,53 @@ __EOF__
 
 	return $?
 }
+
+# Create an EVM/IMA signing key that is also a key of a self-signed CA
+# @param1: The key algorithm; must be a name that OpenSSL command line tool
+#          accepts: rsa:2048, rsa:3072, rsa:4096, prime256v1
+ima_gen_signing_key_selfsigned()
+{
+	GENKEY=x509_evm.genkey
+
+	ossl_keyalgo=$(get_ossl_keyalgo "$keyalgo")
+	if [ -z "$ossl_keyalgo" ]; then
+		echo "Error: Unsupported key algorithm $keyalgo." >&2
+		return 1
+	fi
+	ossl_keyalgo_detail=$(get_ossl_keyalgo_detail "$keyalgo")
+
+	cat << __EOF__ >$GENKEY
+[ req ]
+distinguished_name = req_distinguished_name
+prompt = no
+string_mask = utf8only
+x509_extensions = myexts
+
+[ req_distinguished_name ]
+O = $(hostname)
+CN = $(whoami) signing key
+emailAddress = $(whoami)@$(hostname)
+
+[ myexts ]
+basicConstraints=critical,CA:FALSE
+keyUsage=digitalSignature
+subjectKeyIdentifier=hash
+authorityKeyIdentifier=keyid
+__EOF__
+
+	openssl req -x509 -new -nodes -utf8 -sha256 -days 3650 -batch -config $GENKEY \
+		-outform DER -out x509_evm.der -keyout privkey_evm.pem \
+		-newkey "${ossl_keyalgo}" \
+		${ossl_keyalgo_detail:+${ossl_keyalgo_detail}} || return $?
+
+	case "$keyalgo" in
+	rsa:*)
+		openssl rsa -pubout -in privkey_evm.pem -out pubkey_evm.pem
+		;;
+	primve256v1|secp384r1|secp521r1)
+		openssl ec -pubout -in privkey_evm.pem -out pubkey_evm.pem
+		;;
+	esac
+
+	return $?
+}
