examples: Create ima_gen_localca function and use it
Create ima_gen_localca function for creating an IMA signing key and use it
by existing scripts. Move code from ima-gen-local-ca-ecc.sh and
ima-gen-local-ca.sh into it.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/examples/functions b/examples/functions
--- a/examples/functions
+++ b/examples/functions
@@ -79,3 +79,48 @@ __EOF__
 		-outform DER -out x509_ima.der
 	return $?
 }
+
+# Create a local CA
+# @param1: The key algorithm; must be a name that OpenSSL command line tool
+#          accepts: rsa:2048, rsa:3072, rsa:4096, prime256v1
+ima_gen_localca()
+{
+	keyalgo="$1"
+
+	GENKEY=ima-local-ca.genkey
+
+	ossl_keyalgo=$(get_ossl_keyalgo "$keyalgo")
+	if [ -z "$ossl_keyalgo" ]; then
+		echo "Error: Unsupported key algorithm $keyalgo." >&2
+		return 1
+	fi
+	ossl_keyalgo_detail=$(get_ossl_keyalgo_detail "$keyalgo")
+
+cat << __EOF__ >$GENKEY
+[ req ]
+distinguished_name = req_distinguished_name
+prompt = no
+string_mask = utf8only
+x509_extensions = v3_ca
+
+[ req_distinguished_name ]
+O = IMA-CA
+CN = IMA/EVM certificate signing key
+emailAddress = ca@ima-ca
+
+[ v3_ca ]
+basicConstraints=CA:TRUE
+subjectKeyIdentifier=hash
+authorityKeyIdentifier=keyid:always,issuer
+keyUsage = cRLSign, keyCertSign
+__EOF__
+
+	openssl req -new -x509 -utf8 -sha256 -days 3650 -batch -config $GENKEY \
+		-outform DER -out ima-local-ca.x509 -keyout ima-local-ca.priv \
+		-newkey "${ossl_keyalgo}" \
+		${ossl_keyalgo_detail:+${ossl_keyalgo_detail}} || return $?
+
+	openssl x509 -inform DER -in ima-local-ca.x509 -out ima-local-ca.pem
+
+	return $?
+}
